language: node_js
node_js: node
cache:
  directories:
    - node_modules
services:
  - postgresql
before_script:
  - psql -c 'create database authors_test;' -U postgres
script:
  - npm install 
  - npm run migrate
  - npm test
after_success:
  - npm run coverage
